version: "3.9"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=phlebitis-app
      - MYSQL_USER=test
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=thisisrootpassword
    volumes:
      - ./.docker/volume/mysql:/var/lib/mysql

  app:
    build: .
    ports:
      - 80:3000
    depends_on:
      - mysql
    volumes:
      - phlebitis-app:/app
    environment:
      - DATABASE_URL=mysql://test:1234@mysql:3306/phlebitis-app

volumes:
  phlebitis-app:
