version: '3.9'
services:
  phlebitis-mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=phlebitis-app
      - MYSQL_USER=test
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=thisisrootpassword
    volumes:
      - phlebitis-db:/var/lib/mysql

  phlebitis-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - phlebitis-mysql
    volumes:
      - phlebitis-app:/app
    environment:
      - DATABASE_URL=mysql://test:1234@phlebitis-mysql:3306/phlebitis-app
volumes:
  phlebitis-db:
  phlebitis-app:
